export const PROPERTIES = [
  {
    id: "prop-001",
    slug: "orchard-view-blvd-toronto",
    status: "Active",
    listedDate: "2025-01-26T10:30:00Z",
    price: 725000,
    city: "Toronto",
    neighborhood: "Yonge and Eglinton",
    address: "58 Orchard View Blvd #1711",
    postalCode: "M4R 0A2",
    propertyType: "Condo",
    beds: 2,
    baths: 2,
    sqft: 850,
    parkingSpots: 1,
    thumbnail: "https://images.unsplash.com/photo-1568605114967-8130f3a36994",
    images: ["https://images.unsplash.com/photo-1568605114967-8130f3a36994"],
    title: "Modern Midtown Condo",
    description: "Bright condo with west-facing views in Midtown Toronto.",
    details: {
      interior: {
        totalBathrooms: 2,
        fullBaths: 2,
        flooring: "Hardwood",
        rooms: [],
      },
      exterior: { parkingSpaces: 1, garage: "Underground" },
      amenities: ["Gym", "Roof Terrace"],
      fees: { maintenance: 550, taxes: 3200 },
    },
  },
  {
    id: "prop-002",
    slug: "queen-west-loft-toronto",
    status: "Active",
    listedDate: "2025-01-25T09:15:00Z",
    price: 899000,
    city: "Toronto",
    neighborhood: "Queen West",
    address: "36 Lisgar St #912",
    postalCode: "M6J 0C7",
    propertyType: "Condo",
    beds: 2,
    baths: 2,
    sqft: 910,
    parkingSpots: 1,
    thumbnail: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688"],
    title: "Queen West Loft",
    description: "Trendy loft in the heart of Queen West.",
    details: {
      interior: {
        totalBathrooms: 2,
        fullBaths: 2,
        flooring: "Concrete",
        rooms: [],
      },
      exterior: { parkingSpaces: 1, garage: "Underground" },
      amenities: ["Concierge"],
      fees: { maintenance: 610, taxes: 3500 },
    },
  },
  {
    id: "prop-003",
    slug: "north-york-condo",
    status: "Active",
    listedDate: "2025-01-24T11:45:00Z",
    price: 679000,
    city: "Toronto",
    neighborhood: "North York",
    address: "5162 Yonge St #2308",
    postalCode: "M2N 0G3",
    propertyType: "Condo",
    beds: 1,
    baths: 1,
    sqft: 620,
    parkingSpots: 1,
    thumbnail: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750"],
    title: "North York High-Rise",
    description: "Steps to subway and shopping.",
    details: {
      interior: {
        totalBathrooms: 1,
        fullBaths: 1,
        flooring: "Laminate",
        rooms: [],
      },
      exterior: { parkingSpaces: 1, garage: "Underground" },
      amenities: ["Gym"],
      fees: { maintenance: 480, taxes: 2800 },
    },
  },
  {
    id: "prop-020",
    slug: "orchard-view-blvd-toronto",
    status: "Active",
    listedDate: "2025-01-26T10:30:00Z",
    price: 725000,
    city: "Toronto",
    neighborhood: "Yonge and Eglinton",
    address: "58 Orchard View Blvd #1711",
    postalCode: "M4R 0A2",
    propertyType: "Condo",
    beds: 2,
    baths: 2,
    sqft: 850,
    parkingSpots: 1,
    thumbnail: "https://images.unsplash.com/photo-1568605114967-8130f3a36994",
    images: ["https://images.unsplash.com/photo-1568605114967-8130f3a36994"],
    title: "Modern Midtown Condo",
    description: "Bright condo with west-facing views in Midtown Toronto.",
    details: {
      interior: {
        totalBathrooms: 2,
        fullBaths: 2,
        flooring: "Hardwood",
        rooms: [],
      },
      exterior: { parkingSpaces: 1, garage: "Underground" },
      amenities: ["Gym", "Roof Terrace"],
      fees: { maintenance: 550, taxes: 3200 },
    },
  },
  {
    id: "prop-021",
    slug: "queen-west-loft-toronto",
    status: "Active",
    listedDate: "2025-01-25T09:15:00Z",
    price: 899000,
    city: "Toronto",
    neighborhood: "Queen West",
    address: "36 Lisgar St #912",
    postalCode: "M6J 0C7",
    propertyType: "Condo",
    beds: 2,
    baths: 2,
    sqft: 910,
    parkingSpots: 1,
    thumbnail: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688"],
    title: "Queen West Loft",
    description: "Trendy loft in the heart of Queen West.",
    details: {
      interior: {
        totalBathrooms: 2,
        fullBaths: 2,
        flooring: "Concrete",
        rooms: [],
      },
      exterior: { parkingSpaces: 1, garage: "Underground" },
      amenities: ["Concierge"],
      fees: { maintenance: 610, taxes: 3500 },
    },
  },
  {
    id: "prop-022",
    slug: "north-york-condo",
    status: "Active",
    listedDate: "2025-01-24T11:45:00Z",
    price: 679000,
    city: "Toronto",
    neighborhood: "North York",
    address: "5162 Yonge St #2308",
    postalCode: "M2N 0G3",
    propertyType: "Condo",
    beds: 1,
    baths: 1,
    sqft: 620,
    parkingSpots: 1,
    thumbnail: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750"],
    title: "North York High-Rise",
    description: "Steps to subway and shopping.",
    details: {
      interior: {
        totalBathrooms: 1,
        fullBaths: 1,
        flooring: "Laminate",
        rooms: [],
      },
      exterior: { parkingSpaces: 1, garage: "Underground" },
      amenities: ["Gym"],
      fees: { maintenance: 480, taxes: 2800 },
    },
  },

  /* ================= MISSISSAUGA ================= */
  {
    id: "prop-004",
    slug: "square-one-condo-mississauga",
    status: "Active",
    listedDate: "2025-01-23T13:10:00Z",
    price: 649000,
    city: "Mississauga",
    neighborhood: "City Centre",
    address: "388 Prince of Wales Dr #2109",
    postalCode: "L5B 0G7",
    propertyType: "Condo",
    beds: 1,
    baths: 1,
    sqft: 620,
    parkingSpots: 1,
    thumbnail: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688"],
    title: "Square One Condo",
    description: "High-floor unit near Square One.",
    details: {
      interior: {
        totalBathrooms: 1,
        fullBaths: 1,
        flooring: "Laminate",
        rooms: [],
      },
      exterior: { parkingSpaces: 1, garage: "Underground" },
      amenities: ["Concierge"],
      fees: { maintenance: 420, taxes: 2600 },
    },
  },
  {
    id: "prop-005",
    slug: "erin-mills-townhouse",
    status: "Active",
    listedDate: "2025-01-22T10:00:00Z",
    price: 829000,
    city: "Mississauga",
    neighborhood: "Erin Mills",
    address: "5100 Winston Churchill Blvd",
    postalCode: "L5M 7C4",
    propertyType: "Townhouse",
    beds: 3,
    baths: 3,
    sqft: 1650,
    parkingSpots: 2,
    thumbnail: "https://images.unsplash.com/photo-1518780664697-55e3ad937233",
    images: ["https://images.unsplash.com/photo-1518780664697-55e3ad937233"],
    title: "Erin Mills Townhome",
    description: "Spacious townhome near schools.",
    details: {
      interior: {
        totalBathrooms: 3,
        fullBaths: 3,
        flooring: "Hardwood",
        rooms: [],
      },
      exterior: { parkingSpaces: 2, garage: "Attached" },
      amenities: ["Playground"],
      fees: { maintenance: 180, taxes: 4100 },
    },
  },

  /* ================= BRAMPTON ================= */
  {
    id: "prop-006",
    slug: "mount-pleasant-detached",
    status: "Active",
    listedDate: "2025-01-21T09:30:00Z",
    price: 999000,
    city: "Brampton",
    neighborhood: "Mount Pleasant",
    address: "14 Creditview Rd",
    postalCode: "L6X 2Z2",
    propertyType: "Single Family",
    beds: 4,
    baths: 3,
    sqft: 2600,
    parkingSpots: 2,
    thumbnail: "https://images.unsplash.com/photo-1570129477492-45c003edd2be",
    images: ["https://images.unsplash.com/photo-1570129477492-45c003edd2be"],
    title: "Detached Family Home",
    description: "Large detached home in Mount Pleasant.",
    details: {
      interior: { totalBathrooms: 3, fullBaths: 3, flooring: "Oak", rooms: [] },
      exterior: { parkingSpaces: 2, garage: "Attached" },
      amenities: ["Finished Basement"],
      fees: { maintenance: 0, taxes: 5200 },
    },
  },

  /* ================= MARKHAM / VAUGHAN ================= */
  {
    id: "prop-007",
    slug: "cornell-townhouse-markham",
    status: "Active",
    listedDate: "2025-01-20T15:00:00Z",
    price: 899000,
    city: "Markham",
    neighborhood: "Cornell",
    address: "22 Fred McLaren Blvd",
    postalCode: "L6B 0H2",
    propertyType: "Townhouse",
    beds: 3,
    baths: 3,
    sqft: 1700,
    parkingSpots: 1,
    thumbnail: "https://images.unsplash.com/photo-1518780664697-55e3ad937233",
    images: ["https://images.unsplash.com/photo-1518780664697-55e3ad937233"],
    title: "Modern Markham Townhome",
    description: "Move-in ready townhome.",
    details: {
      interior: {
        totalBathrooms: 3,
        fullBaths: 3,
        flooring: "Laminate",
        rooms: [],
      },
      exterior: { parkingSpaces: 1, garage: "Attached" },
      amenities: ["Park Nearby"],
      fees: { maintenance: 150, taxes: 4300 },
    },
  },
  {
    id: "prop-008",
    slug: "vmc-condo-vaughan",
    status: "Active",
    listedDate: "2025-01-19T12:40:00Z",
    price: 710000,
    city: "Vaughan",
    neighborhood: "Vaughan Metropolitan Centre",
    address: "898 Portage Pkwy #3505",
    postalCode: "L4K 0J6",
    propertyType: "Condo",
    beds: 2,
    baths: 2,
    sqft: 780,
    parkingSpots: 1,
    thumbnail: "https://images.unsplash.com/photo-1568605114967-8130f3a36994",
    images: ["https://images.unsplash.com/photo-1568605114967-8130f3a36994"],
    title: "VMC High-Rise Condo",
    description: "Steps from subway.",
    details: {
      interior: {
        totalBathrooms: 2,
        fullBaths: 2,
        flooring: "Laminate",
        rooms: [],
      },
      exterior: { parkingSpaces: 1, garage: "Underground" },
      amenities: ["Gym"],
      fees: { maintenance: 520, taxes: 3000 },
    },
  },

  {
    id: "prop-009",
    slug: "ancaster-home-hamilton",
    status: "Active",
    listedDate: "2025-01-18T10:00:00Z",
    price: 679000,
    city: "Hamilton",
    neighborhood: "Ancaster",
    address: "88 Wilson St E",
    postalCode: "L9G 2B8",
    propertyType: "Single Family",
    beds: 3,
    baths: 2,
    sqft: 1900,
    parkingSpots: 2,
    thumbnail: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6"],
    title: "Ancaster Family Home",
    description: "Quiet street with mature trees.",
    details: {
      interior: {
        totalBathrooms: 2,
        fullBaths: 2,
        flooring: "Hardwood",
        rooms: [],
      },
      exterior: { parkingSpaces: 2, garage: "Attached" },
      amenities: ["Fireplace"],
      fees: { maintenance: 0, taxes: 3900 },
    },
  },
];
