export const PROPERTIES = [
  {
    id: "prop-001",
    slug: "58-orchard-view-blvd-toronto",
    status: "Active",
    price: 725000,
    city: "Toronto",
    neighborhood: "Yonge and Eglinton",
    address: "58 Orchard View Blvd #1711",
    postalCode: "M4R 0A2",
    propertyType: "Condo",
    beds: 2,
    baths: 2,
    sqft: 850,
    parkingSpots: 1,
    thumbnail: "https://images.unsplash.com/photo-1568605114967-8130f3a36994",
    images: [
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    ],
    title: "Single Family in Yonge and Eglinton",
    description:
      "Welcome to your urban oasis in the heart of Midtown Toronto. This stunning condo features a great layout with west-facing windows.",
    details: {
      interior: {
        totalBathrooms: 2,
        fullBaths: 2,
        flooring: "Hardwood",
        rooms: [
          { name: "Living Room", dimensions: "20.3 x 11.1 ft" },
          { name: "Kitchen", dimensions: "15.7 x 10.4 ft" },
        ],
      },
      exterior: { parkingSpaces: 1, garage: "Underground" },
      amenities: ["Central Air", "Gym", "Roof Terrace"],
      fees: { maintenance: 550, taxes: 3200 },
    },
  },
  {
    id: "prop-002",
    slug: "120-marine-drive-vancouver",
    status: "Active",
    price: 1250000,
    city: "Vancouver",
    neighborhood: "Kitsilano",
    address: "120 Marine Drive",
    postalCode: "V6J 1A1",
    propertyType: "Single Family ",
    beds: 3,
    baths: 3,
    sqft: 1800,
    parkingSpots: 2,
    thumbnail: "https://images.unsplash.com/photo-1570129477492-45c003edd2be",
    images: ["https://images.unsplash.com/photo-1570129477492-45c003edd2be"],
    title: "Ocean View Modern Home",
    description:
      "Exquisite modern living with panoramic ocean views and luxury finishes throughout.",
    details: {
      interior: {
        totalBathrooms: 3,
        fullBaths: 3,
        flooring: "Polished Concrete",
        rooms: [{ name: "Master Suite", dimensions: "18 x 20 ft" }],
      },
      exterior: { parkingSpaces: 2, garage: "Attached" },
      amenities: ["Ocean View", "Smart Home", "EV Charger"],
      fees: { maintenance: 0, taxes: 5800 },
    },
  },
  {
    id: "prop-003",
    slug: "45-rue-st-denis-montreal",
    status: "Active",
    price: 549000,
    city: "Montreal",
    neighborhood: "Plateau",
    address: "45 Rue St-Denis",
    postalCode: "H2X 1E7",
    propertyType: "Townhouse",
    beds: 2,
    baths: 1,
    sqft: 1100,
    parkingSpots: 0,
    thumbnail: "https://images.unsplash.com/photo-1518780664697-55e3ad937233",
    images: ["https://images.unsplash.com/photo-1518780664697-55e3ad937233"],
    title: "Charming Plateau Townhouse",
    description:
      "Classic Montreal charm with exposed brick and private outdoor courtyard.",
    details: {
      interior: {
        totalBathrooms: 1,
        fullBaths: 1,
        flooring: "Original Pine",
        rooms: [{ name: "Dining Room", dimensions: "12 x 14 ft" }],
      },
      exterior: { parkingSpaces: 0, garage: "Street" },
      amenities: ["Private Patio", "Exposed Brick"],
      fees: { maintenance: 120, taxes: 2800 },
    },
  },
  {
    id: "prop-004",
    slug: "88-stephen-ave-calgary",
    status: "Active",
    price: 415000,
    city: "Calgary",
    neighborhood: "Downtown",
    address: "88 Stephen Ave",
    postalCode: "T2P 1J8",
    propertyType: "Condo",
    beds: 1,
    baths: 1,
    sqft: 650,
    parkingSpots: 1,
    thumbnail: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688"],
    title: "High-Rise Executive Suite",
    description: "Floor-to-ceiling windows with incredible city skyline views.",
    details: {
      interior: {
        totalBathrooms: 1,
        fullBaths: 1,
        flooring: "Laminate",
        rooms: [],
      },
      exterior: { parkingSpaces: 1, garage: "Heated" },
      amenities: ["Concierge", "Underground Parking"],
      fees: { maintenance: 480, taxes: 2100 },
    },
  },
  {
    id: "prop-005",
    slug: "22-bay-st-ottawa",
    status: "Active",
    price: 890000,
    city: "Ottawa",
    neighborhood: "Glebe",
    address: "22 Bay St",
    postalCode: "K1S 3V8",
    propertyType: "Single Family",
    beds: 4,
    baths: 3,
    sqft: 2400,
    parkingSpots: 2,
    thumbnail: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6"],
    title: "Heritage District Family Home",
    description: "Fully renovated heritage home in the heart of the Glebe.",
    details: {
      interior: {
        totalBathrooms: 3,
        fullBaths: 3,
        flooring: "Oak",
        rooms: [{ name: "Library", dimensions: "10 x 12 ft" }],
      },
      exterior: { parkingSpaces: 2, garage: "Detached" },
      amenities: ["Fireplace", "Wine Cellar"],
      fees: { maintenance: 0, taxes: 6200 },
    },
  },
  {
    id: "prop-006",
    slug: "58-orchard-view-blvd-toronto",
    status: "Active",
    price: 725000,
    city: "Toronto",
    neighborhood: "Yonge and Eglinton",
    address: "58 Orchard View Blvd #1711",
    postalCode: "M4R 0A2",
    propertyType: "Condo",
    beds: 2,
    baths: 2,
    sqft: 850,
    parkingSpots: 1,
    thumbnail: "https://images.unsplash.com/photo-1568605114967-8130f3a36994",
    images: [
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    ],
    title: "Single Family in Yonge and Eglinton",
    description:
      "Welcome to your urban oasis in the heart of Midtown Toronto. This stunning condo features a great layout with west-facing windows.",
    details: {
      interior: {
        totalBathrooms: 2,
        fullBaths: 2,
        flooring: "Hardwood",
        rooms: [
          { name: "Living Room", dimensions: "20.3 x 11.1 ft" },
          { name: "Kitchen", dimensions: "15.7 x 10.4 ft" },
        ],
      },
      exterior: { parkingSpaces: 1, garage: "Underground" },
      amenities: ["Central Air", "Gym", "Roof Terrace"],
      fees: { maintenance: 550, taxes: 3200 },
    },
  },
  {
    id: "prop-007",
    slug: "120-marine-drive-vancouver",
    status: "Active",
    price: 1250000,
    city: "Vancouver",
    neighborhood: "Kitsilano",
    address: "120 Marine Drive",
    postalCode: "V6J 1A1",
    propertyType: "Single Family",
    beds: 3,
    baths: 3,
    sqft: 1800,
    parkingSpots: 2,
    thumbnail: "https://images.unsplash.com/photo-1570129477492-45c003edd2be",
    images: ["https://images.unsplash.com/photo-1570129477492-45c003edd2be"],
    title: "Ocean View Modern Home",
    description:
      "Exquisite modern living with panoramic ocean views and luxury finishes throughout.",
    details: {
      interior: {
        totalBathrooms: 3,
        fullBaths: 3,
        flooring: "Polished Concrete",
        rooms: [{ name: "Master Suite", dimensions: "18 x 20 ft" }],
      },
      exterior: { parkingSpaces: 2, garage: "Attached" },
      amenities: ["Ocean View", "Smart Home", "EV Charger"],
      fees: { maintenance: 0, taxes: 5800 },
    },
  },
  {
    id: "prop-008",
    slug: "45-rue-st-denis-montreal",
    status: "Active",
    price: 549000,
    city: "Montreal",
    neighborhood: "Plateau",
    address: "45 Rue St-Denis",
    postalCode: "H2X 1E7",
    propertyType: "Townhouse",
    beds: 2,
    baths: 1,
    sqft: 1100,
    parkingSpots: 0,
    thumbnail: "https://images.unsplash.com/photo-1518780664697-55e3ad937233",
    images: ["https://images.unsplash.com/photo-1518780664697-55e3ad937233"],
    title: "Charming Plateau Townhouse",
    description:
      "Classic Montreal charm with exposed brick and private outdoor courtyard.",
    details: {
      interior: {
        totalBathrooms: 1,
        fullBaths: 1,
        flooring: "Original Pine",
        rooms: [{ name: "Dining Room", dimensions: "12 x 14 ft" }],
      },
      exterior: { parkingSpaces: 0, garage: "Street" },
      amenities: ["Private Patio", "Exposed Brick"],
      fees: { maintenance: 120, taxes: 2800 },
    },
  },
  {
    id: "prop-009",
    slug: "88-stephen-ave-calgary",
    status: "Active",
    price: 415000,
    city: "Calgary",
    neighborhood: "Downtown",
    address: "88 Stephen Ave",
    postalCode: "T2P 1J8",
    propertyType: "Condo",
    beds: 1,
    baths: 1,
    sqft: 650,
    parkingSpots: 1,
    thumbnail: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688"],
    title: "High-Rise Executive Suite",
    description: "Floor-to-ceiling windows with incredible city skyline views.",
    details: {
      interior: {
        totalBathrooms: 1,
        fullBaths: 1,
        flooring: "Laminate",
        rooms: [],
      },
      exterior: { parkingSpaces: 1, garage: "Heated" },
      amenities: ["Concierge", "Underground Parking"],
      fees: { maintenance: 480, taxes: 2100 },
    },
  },

  {
    id: "prop-011",
    slug: "22-bay-st-ottawa",
    status: "Active",
    price: 890000,
    city: "Calgary",
    neighborhood: "Glebe",
    address: "22 Bay St",
    postalCode: "K1S 3V8",
    propertyType: "Single Family",
    beds: 4,
    baths: 3,
    sqft: 2400,
    parkingSpots: 2,
    thumbnail: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6"],
    title: "Heritage District Family Home",
    description: "Fully renovated heritage home in the heart of the Glebe.",
    details: {
      interior: {
        totalBathrooms: 3,
        fullBaths: 3,
        flooring: "Oak",
        rooms: [{ name: "Library", dimensions: "10 x 12 ft" }],
      },
      exterior: { parkingSpaces: 2, garage: "Detached" },
      amenities: ["Fireplace", "Wine Cellar"],
      fees: { maintenance: 0, taxes: 6200 },
    },
  },
  {
    id: "prop-012",
    slug: "22-bay-st-ottawa",
    status: "Active",
    price: 890000,
    city: "Calgary",
    neighborhood: "Glebe",
    address: "22 Bay St",
    postalCode: "K1S 3V8",
    propertyType: "Single Family",
    beds: 4,
    baths: 3,
    sqft: 2400,
    parkingSpots: 2,
    thumbnail: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6"],
    title: "Heritage District Family Home",
    description: "Fully renovated heritage home in the heart of the Glebe.",
    details: {
      interior: {
        totalBathrooms: 3,
        fullBaths: 3,
        flooring: "Oak",
        rooms: [{ name: "Library", dimensions: "10 x 12 ft" }],
      },
      exterior: { parkingSpaces: 2, garage: "Detached" },
      amenities: ["Fireplace", "Wine Cellar"],
      fees: { maintenance: 0, taxes: 6200 },
    },
  },
  {
    id: "prop-013",
    slug: "22-bay-st-ottawa",
    status: "Active",
    price: 890000,
    city: "Calgary",
    neighborhood: "Glebe",
    address: "22 Bay St",
    postalCode: "K1S 3V8",
    propertyType: "Single Family",
    beds: 4,
    baths: 3,
    sqft: 2400,
    parkingSpots: 2,
    thumbnail: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6"],
    title: "Heritage District Family Home",
    description: "Fully renovated heritage home in the heart of the Glebe.",
    details: {
      interior: {
        totalBathrooms: 3,
        fullBaths: 3,
        flooring: "Oak",
        rooms: [{ name: "Library", dimensions: "10 x 12 ft" }],
      },
      exterior: { parkingSpaces: 2, garage: "Detached" },
      amenities: ["Fireplace", "Wine Cellar"],
      fees: { maintenance: 0, taxes: 6200 },
    },
  },
];
